name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master      

jobs:
  build-and-push-docker-images:
    runs-on: ubuntu-latest  # Cambiado a Linux

    steps:
      # Paso 1: Checkout del c칩digo
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar entorno para Python y ejecutar tests
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r vote/requirements.txt

      - name: Run Python unit tests
        run: |
          cd vote
          python -m unittest discover -s . -p "test_*.py"

      # Paso 3: Configurar entorno para Node.js y ejecutar tests
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node.js dependencies for `result`
        run: |
          cd result
          npm install
 
      - name: Run Node.js unit tests for `result`
        run: |
          cd result
          chmod +x ./node_modules/.bin/jest   
          npm test

      # Paso 4: Iniciar sesi칩n en DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 5: Construir y etiquetar im치genes Docker
      - name: Build Docker images
        run: |
          docker compose build

      - name: Tag Docker images
        run: |
          docker tag example-voting-app-vote:latest ${{ secrets.DOCKER_USERNAME }}/example-voting-app-vote:latest
          docker tag example-voting-app-result:latest ${{ secrets.DOCKER_USERNAME }}/example-voting-app-result:latest
          docker tag example-voting-app-worker:latest ${{ secrets.DOCKER_USERNAME }}/example-voting-app-worker:latest

      # Paso 6: Subir las im치genes a DockerHub
      - name: Push Docker images to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/example-voting-app-vote:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/example-voting-app-result:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/example-voting-app-worker:latest

